### ISSUE TITLE
Firebase connection Error

### ISSUE THREAD

**Issue by monastyrskiiden** [iamshaunjp/React-Redux-Firebase-App#4]
With react-redux v6 and new React Context API, react-redux-firebase has changed. Here's an official [Migration Guide](http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html). Please update your tutorial.

**Comment by stevehwg** [comment]
I think react-redux-firebase is still on v3 alpha branch [here](https://github.com/prescottprue/react-redux-firebase). It's not fully implemented yet but you can definitely spent the time to connect to firebase.

Edit: I was able to create project in firestore but I wasn't able to get auth to work even with the migration guide. I was able to get firebase context but I was lost afterwards...

**Comment by monastyrskiiden** [comment]
> I think react-redux-firebase is still on v3 alpha branch [here](https://github.com/prescottprue/react-redux-firebase). It's not fully implemented yet but you can definitely spent the time to connect to firebase.
> 
> Edit: I was able to create project in firestore but I wasn't able to get auth to work even with the migration guide. I was able to get firebase context but I was lost afterwards...

Thank's for your answer, I'll try to work around this problem.
