### ISSUE TITLE
upgrading to v3 react redux firestore

### ISSUE THREAD

**Issue by TeoAlmonte** [iamshaunjp/React-Redux-Firebase-App#8]
re: Episode 19 of the firebase app.

I've been trying to complete the project with v3 of react-redux-firebase using these docs http://docs.react-redux-firebase.com/history/v3.0.0/docs/v3-migration-guide.html and I am getting stumped with upgrading.

I am going to complete with v2 for now but would be very helpful if someone has successfully upgraded to v3

Any chance someone else has done this? I keep getting errors.

**Comment by TeoAlmonte** [comment]
actually got it 😅

**Comment by mubeenmazhar** [comment]
How?

**Comment by GarethCairns** [comment]
@TeoAlmonte please post your changes, that would really help.
